<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

# Lab 3.1.1 
# *Data Wrangling and Munging with Pandas*

## Part 1: Wrangling Data

The term "data wrangling" is analogous to capturing wild horses and getting them into a fenced area; the horses are data and the fencing is your computer. The more common data wrangling tasks include:

- reading flat files
- reading Excel files
- downloading from web pages
  - csv
  - html
  - json

In [1]:
import numpy as np
import pandas as pd


*It is good practice to display the library version numbers for future reference:*

In [2]:
print('Numpy: ', np.__version__)
print('Pandas: ', pd.__version__)

Numpy:  1.19.2
Pandas:  1.1.5


### CSV Files

Below are three attempts to load the file "bikeshare.csv" into a DataFrame named `bikes`. Why are they wrong?

In [3]:
# wrong:
bikes = pd.read_table('bikeshare.csv', header = None)
print(bikes.head())
print()

# wrong:
bikes = pd.read_table('bikeshare.csv', header = 1)
print(bikes.head())
print()


# wrong:
bikes = pd.read_table('bikeshare.csv', header = 0)
print(bikes.head())

                                                   0
0  instant,dteday,season,yr,mnth,hr,holiday,weekd...
1  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,...
2  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...
3  3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.8,0...
4  4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,...

  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0,3,13,16
0  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...     
1  3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.8,0...     
2  4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,...     
3  5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,...     
4  6,2011-01-01,1,0,1,5,0,6,0,2,0.24,0.2576,0.75,...     

  instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,...                                                                   
1  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...                                        

?:
ANSWER: Case 1 treats headings as just another data row. Case 2 treats the 1st data row as the column header. Case 3 gets the header right (row 0), but reads each row as a single column (Nb. the other two make that same mistake). 

Load the file "bikeshare.csv" into a DataFrame named `bikes`, and confirm that it was loaded properly:

In [4]:
#ANSWER:
bikes = pd.read_csv('bikeshare.csv')
bikes

instant      dteday  season  yr  mnth  hr  holiday  weekday  \
0            1  2011-01-01       1   0     1   0        0        6   
1            2  2011-01-01       1   0     1   1        0        6   
2            3  2011-01-01       1   0     1   2        0        6   
3            4  2011-01-01       1   0     1   3        0        6   
4            5  2011-01-01       1   0     1   4        0        6   
...        ...         ...     ...  ..   ...  ..      ...      ...   
17374    17375  2012-12-31       1   1    12  19        0        1   
17375    17376  2012-12-31       1   1    12  20        0        1   
17376    17377  2012-12-31       1   1    12  21        0        1   
17377    17378  2012-12-31       1   1    12  22        0        1   
17378    17379  2012-12-31       1   1    12  23        0        1   

       workingday  weathersit  temp   atemp   hum  windspeed  casual  \
0               0           1  0.24  0.2879  0.81     0.0000       3   
1               0           1  0.22  0.2727  0.80     0.0000       8   
2               0           1  0.22  0.2727  0.80     0.0000       5   
3               0           1  0.24  0.2879  0.75     0.0000       3   
4               0           1  0.24  0.2879  0.75     0.0000       0   
...           ...         ...   ...     ...   ...        ...     ...   
17374           1           2  0.26  0.2576  0.60     0.1642      11   
17375           1           2  0.26  0.2576  0.60     0.1642       8   
17376           1           1  0.26  0.2576  0.60     0.1642       7   
17377           1           1  0.26  0.2727  0.56     0.1343      13   
17378           1           1  0.26  0.2727  0.65     0.1343      12   

       registered  cnt  
0              13   16  
1              32   40  
2              27   32  
3              10   13  
4               1    1  
...           ...  ...  
17374         108  119  
17375          81   89  
17376          83   90  
17377          48   61  
17378          37   49  

[17379 rows x 17 columns]

Note that we could have used `read.csv()` above. When is `read_table()` necessary?

?:
ANSWER: When `sep` is not the comma character, or we need fine control that `read.csv()` does not provide.

Flat files can be full of surprises. Here are some issues to watch out for:

- separator character is something other than the comma
  - ";", "|", and tab are popular
- newline character is something other than what the O/S expects 
  - Tip: Don't hard-code the character codes for carriage returns, linefeeds, etc. Use Python's built-in representation instead (e.g. Python translates "\n" to the newline character and "\t" to the tab character on any O/S).
- truncated lines
  - if there are empty fields at the end of a line it is possible that their separators will be missing, resulting in a "jagged" file
- embedded commas or quotes
  - a free-text field containing embedded commas may split into separate fields on input
  - a free-text field containing embedded quotes may not parse correctly
- unescaped characters
  - the "\" character indicates a control code to Python, which will break the I/O
    - e.g. the substring "\u0123" will be interpreted as Unicode(0123) -- which may not be what the file creator intended
  - these may need to be fixed by loading whole strings and then parsing into a new data frame
  
Tip: Most issues can be delth with by correctly specifying the parameters of the function you use to load the file. Read the doco before reading the data!

### Reading Excel Files

In [5]:
from pandas import ExcelFile  # Nb. Need to install xlrd from conda (it does not automatically install with pandas)

In [6]:
df = pd.read_excel('Iris.xls', sheet_name = 'Data')
df

Species_No  Petal_width  Petal_length  Sepal_width  Sepal_length  \
0             1          0.2           1.4          3.5           5.1   
1             1          0.2           1.4          3.0           4.9   
2             1          0.2           1.3          3.2           4.7   
3             1          0.2           1.5          3.1           4.6   
4             1          0.2           1.4          3.6           5.0   
..          ...          ...           ...          ...           ...   
145           3          2.3           5.2          3.0           6.7   
146           3          1.9           5.0          2.5           6.3   
147           3          2.0           5.2          3.0           6.5   
148           3          2.3           5.4          3.4           6.2   
149           3          1.8           5.1          3.0           5.9   

    Species_name  
0         Setosa  
1         Setosa  
2         Setosa  
3         Setosa  
4         Setosa  
..           ...  
145    Verginica  
146    Verginica  
147    Verginica  
148    Verginica  
149    Verginica  

[150 rows x 6 columns]

So, this file appears to have an embedded table of aggregates on the same sheet as the raw data (a naughty but common practice amongst analysts).

It is usually better to load data correctly than to meddle with the source file or load it 'warts and all' and then try to parse it in code. The Pandas functions for reading files have parameters that provide the control we need. For ecxample, we could make multiple calls to `read_excel()`, using combinations of the `header`, `usecols`, `skiprows`, `nrows`, and `skipfooter` parameters to load one table at a time from a spreadsheet with multiple tables.

Load the above file without the unwanted columns:

In [7]:
#ANSWER

# nrows : int, default None
#    Number of rows to parse.


df_usecol = pd.read_excel('iris.xls',  sheet_name = 'Data', usecols = "A,B,C, E")
df_usecol


Species_No  Petal_width  Petal_length  Sepal_length
0             1          0.2           1.4           5.1
1             1          0.2           1.4           4.9
2             1          0.2           1.3           4.7
3             1          0.2           1.5           4.6
4             1          0.2           1.4           5.0
..          ...          ...           ...           ...
145           3          2.3           5.2           6.7
146           3          1.9           5.0           6.3
147           3          2.0           5.2           6.5
148           3          2.3           5.4           6.2
149           3          1.8           5.1           5.9

[150 rows x 4 columns]

In [8]:
# nrows : int, default None
#  Number of rows to parse.



df_nrows= pd.read_excel('iris.xls', sheet_name = 'Data', nrows = 5 )
df_nrows


Species_No  Petal_width  Petal_length  Sepal_width  Sepal_length  \
0           1          0.2           1.4          3.5           5.1   
1           1          0.2           1.4          3.0           4.9   
2           1          0.2           1.3          3.2           4.7   
3           1          0.2           1.5          3.1           4.6   
4           1          0.2           1.4          3.6           5.0   

  Species_name  
0       Setosa  
1       Setosa  
2       Setosa  
3       Setosa  
4       Setosa

In [9]:
# header : int, list of int, default 0
#   Row (0-indexed) to use for the column labels of the parsed
#    DataFrame. If a list of integers is passed those row positions will
#   be combined into a ``MultiIndex``. Use None if there is no header.

df_header = pd.read_excel("iris.xls", sheet_name= 'Data', header = (0,1) )
df_header

Species_No Petal_width Petal_length Sepal_width Sepal_length Species_name
             1         0.2          1.4         3.5          5.1       Setosa
0            1         0.2          1.4         3.0          4.9       Setosa
1            1         0.2          1.3         3.2          4.7       Setosa
2            1         0.2          1.5         3.1          4.6       Setosa
3            1         0.2          1.4         3.6          5.0       Setosa
4            1         0.4          1.7         3.9          5.4       Setosa
..         ...         ...          ...         ...          ...          ...
144          3         2.3          5.2         3.0          6.7    Verginica
145          3         1.9          5.0         2.5          6.3    Verginica
146          3         2.0          5.2         3.0          6.5    Verginica
147          3         2.3          5.4         3.4          6.2    Verginica
148          3         1.8          5.1         3.0          5.9    Verginica

[149 rows x 6 columns]

In [10]:
# skiprows : list-like
#  Rows to skip at the beginning (0-indexed)

df_skiprows = pd.read_excel('iris.xls', sheet_name= 'Data', header = 0, nrows= 5, skiprows = (100))
df_skiprows

2  1.3  4.1  2.8  5.7  Versicolor
0  3  2.5  6.0  3.3  6.3   Verginica
1  3  1.9  5.1  2.7  5.8   Verginica
2  3  2.1  5.9  3.0  7.1   Verginica
3  3  1.8  5.6  2.9  6.3   Verginica
4  3  2.2  5.8  3.0  6.5   Verginica

# CLARIFICATION REQUIRED - using skiprow and header arguments in read_excel : original header = 0 is lost whenever skip row is used.

In [11]:
# skipfooter : int, default 0
 #   Rows at the end to skip (0-indexed)
    
df_skipfooter = pd.read_excel('iris.xls', sheet_name = "Data", skipfooter = 148) 
df_skipfooter

Species_No  Petal_width  Petal_length  Sepal_width  Sepal_length  \
0           1          0.2           1.4          3.5           5.1   
1           1          0.2           1.4          3.0           4.9   

  Species_name  
0       Setosa  
1       Setosa

### Importing Data Directly from the Web

We usually want to store a local copy of a data file that we download from the Web, but when data retention is not a priority it is convenient to download the data directly into our running Python environment.

#### Importing Text Files from the Web

The web is the 'wild west' of data formats. However, we can usually expect good behaviour from files that are automatically generated by a service, such as the earthquake report:

In [12]:
df = pd.read_csv('https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_hour.csv')
df.head()

Empty DataFrame
Columns: [time, latitude, longitude, depth, mag, magType, nst, gap, dmin, rms, net, id, updated, place, type, horizontalError, depthError, magError, magNst, status, locationSource, magSource]
Index: []

[0 rows x 22 columns]

#### Importing HTML Files from the Web

Working with unstructured HTML files relies heavily on library functions. This one, however, is well-structured:

In [14]:
url = 'http://www.fdic.gov/bank/individual/failed/banklist.html'
df = pd.read_html(url)
df

ImportError: BeautifulSoup4 (bs4) not found, please install it

#### Importing XML Files from the Web

XML files are semi-structured, but you're at the mercy of the file creator. If every record has the same format it will be much easier, but practical applications often require a lot of custom code. Here is an example that includes a nice parser class: http://www.austintaylor.io/lxml/python/pandas/xml/dataframe/2016/07/08/convert-xml-to-pandas-dataframe/

#### Importing JSON Files from the Web

Like XML, JSON files are semi-structured and may require work to capture the schema into a dataframe. Here is a simple example: 

In [15]:
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/data.json'

# Load the first sheet of the JSON file into a data frame
df = pd.read_json(url, orient = 'columns')
df.head()

integer            datetime  category
0        5 2015-01-01 00:00:00         0
1        5 2015-01-01 00:00:01         0
2        9 2015-01-01 00:00:02         0
3        6 2015-01-01 00:00:03         0
4        6 2015-01-01 00:00:04         0

## Part 2: Data Munging

Data munging is manipulating data to get it into a form that we can start running analyses on (which usually means getting the data into a DataFrame). Before we get to this stage, we may need to remove headers or footers, transpose columns to rows, split wide data tables into long ones, and so on. (Nb. Excel files can be particularly troublesome, because users can format their data in mixed, complex shapes.) Essentially, we need to follow Hadley Wickham's guidelines for tidy datasets (http://vita.had.co.nz/papers/tidy-data.html):

The end goal of the cleaning data process:

- each variable should be in one column
- each observation should comprise one row
- each type of observational unit should form one table
- include key columns for linking multiple tables
- the top row contains (sensible) variable names
- in general, save data as one file per table


### Dataset Morphology

Once we have our dataset in a DataFrame (or Series, if our data is only 1-dimensional), we can start examining its size and content.

How many rows and columns are in `bikes`?

In [16]:
#ANSWER

bikes.shape

(17379, 17)

What are the column names in `bikes`?

In [17]:
#ANSWER

bikes.columns

Index(['instant', 'dteday', 'season', 'yr', 'mnth', 'hr', 'holiday', 'weekday',
       'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed',
       'casual', 'registered', 'cnt'],
      dtype='object')

What are the data types of these columns?

In [18]:
#ANSWER
bikes.dtypes

instant         int64
dteday         object
season          int64
yr              int64
mnth            int64
hr              int64
holiday         int64
weekday         int64
workingday      int64
weathersit      int64
temp          float64
atemp         float64
hum           float64
windspeed     float64
casual          int64
registered      int64
cnt             int64
dtype: object

What is the (row) index for this DataFrame?

In [19]:
#ANSWER

bikes.index


RangeIndex(start=0, stop=17379, step=1)

https://www.dataquest.io/blog/python-json-tutorial/

## Slicing and Dicing

It is often preferable to refer to DataFrame columns by name, but there is more than one way to do this. 
Do `bikes['season']` and `bikes[['season']]` give the same object? Demonstrate:

In [20]:
#ANSWER

bikes['season'] == bikes[['season']]

season      0      1      2      3      4      5      6      7      8  \
0       False  False  False  False  False  False  False  False  False  False   
1       False  False  False  False  False  False  False  False  False  False   
2       False  False  False  False  False  False  False  False  False  False   
3       False  False  False  False  False  False  False  False  False  False   
4       False  False  False  False  False  False  False  False  False  False   
...       ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
17374   False  False  False  False  False  False  False  False  False  False   
17375   False  False  False  False  False  False  False  False  False  False   
17376   False  False  False  False  False  False  False  False  False  False   
17377   False  False  False  False  False  False  False  False  False  False   
17378   False  False  False  False  False  False  False  False  False  False   

       ...  17369  17370  17371  17372  17373  17374  17375  17376  17377  \
0      ...  False  False  False  False  False  False  False  False  False   
1      ...  False  False  False  False  False  False  False  False  False   
2      ...  False  False  False  False  False  False  False  False  False   
3      ...  False  False  False  False  False  False  False  False  False   
4      ...  False  False  False  False  False  False  False  False  False   
...    ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
17374  ...  False  False  False  False  False  False  False  False  False   
17375  ...  False  False  False  False  False  False  False  False  False   
17376  ...  False  False  False  False  False  False  False  False  False   
17377  ...  False  False  False  False  False  False  False  False  False   
17378  ...  False  False  False  False  False  False  False  False  False   

       17378  
0      False  
1      False  
2      False  
3      False  
4      False  
...      ...  
17374  False  
17375  False  
17376  False  
17377  False  
17378  False  

[17379 rows x 17380 columns]

In [21]:
type(bikes['season'])

pandas.core.series.Series

In [22]:
type(bikes[['season']])

pandas.core.frame.DataFrame

How would we use object notation to show the first 4 rows of `atemp`?

In [24]:
#ANSWER

bikes.atemp[0:4]

0    0.2879
1    0.2727
2    0.2727
3    0.2879
Name: atemp, dtype: float64

Algorithms that loop over multiple columns often access DataFrame columns by index. However, none of the following work (try them out by uncommenting / removing the "#E: " ): 

In [ ]:
#bikes[[0]]
#E: bikes[0]
#E: bikes[0,0]
#E: bikes[[0,0]]

What is the correct way to access the 1st row of the DataFrame by its index?

In [30]:
#ANSWER

bikes[:1]

instant      dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1   0        0        6           0   

   weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  
0           1  0.24  0.2879  0.81        0.0       3          13   16

What is the correct way to access the 2nd column of the DataFrame by its index?

In [36]:
#ANSWER

bikes.iloc[:,1]

0        2011-01-01
1        2011-01-01
2        2011-01-01
3        2011-01-01
4        2011-01-01
            ...    
17374    2012-12-31
17375    2012-12-31
17376    2012-12-31
17377    2012-12-31
17378    2012-12-31
Name: dteday, Length: 17379, dtype: object

## Handling Missing Values

What is the Pandas `isnull` function for? 

?
ANSWER:

We can apply `isnull` to the `bikes` DataFrame to show the result for every element:

In [37]:
bikes.isnull()

instant  dteday  season     yr   mnth     hr  holiday  weekday  \
0        False   False   False  False  False  False    False    False   
1        False   False   False  False  False  False    False    False   
2        False   False   False  False  False  False    False    False   
3        False   False   False  False  False  False    False    False   
4        False   False   False  False  False  False    False    False   
...        ...     ...     ...    ...    ...    ...      ...      ...   
17374    False   False   False  False  False  False    False    False   
17375    False   False   False  False  False  False    False    False   
17376    False   False   False  False  False  False    False    False   
17377    False   False   False  False  False  False    False    False   
17378    False   False   False  False  False  False    False    False   

       workingday  weathersit   temp  atemp    hum  windspeed  casual  \
0           False       False  False  False  False      False   False   
1           False       False  False  False  False      False   False   
2           False       False  False  False  False      False   False   
3           False       False  False  False  False      False   False   
4           False       False  False  False  False      False   False   
...           ...         ...    ...    ...    ...        ...     ...   
17374       False       False  False  False  False      False   False   
17375       False       False  False  False  False      False   False   
17376       False       False  False  False  False      False   False   
17377       False       False  False  False  False      False   False   
17378       False       False  False  False  False      False   False   

       registered    cnt  
0           False  False  
1           False  False  
2           False  False  
3           False  False  
4           False  False  
...           ...    ...  
17374       False  False  
17375       False  False  
17376       False  False  
17377       False  False  
17378       False  False  

[17379 rows x 17 columns]

However, we usually start at a higher level. How many nulls are in `bikes` altogether?

In [38]:
#ANSWER
# Using a single sum, you get the count of NaN's for each column. The second sum, sums those column sums.
bikes.isnull().sum().sum()


0

If this result were nonzero we would next want to find out which columns contained nulls. How can this be done in one line of code?

In [39]:
#ANSWER

bikes.isna().sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
hr            0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

What is the Numpy object `nan` used for? (Write a descriptive answer.)

?
ANSWER: Marking a data point as invalid.

Write (and verify) a function that performs scalar division with built-in handling of the edge case (i.e. return a value instead of just trapping the error):

In [40]:
#ANSWER

def divider(a,b):
    if b == 0:
        print(' this gives error')
    else:
        result = (a/b)
        return result



In [42]:
divider(1,6)

0.16666666666666666

In [43]:
divider(2,0)

 this gives error


Apply the Pandas `isna` function to the following data objects:

In [44]:
x = 2.3
y = np.nan
print(x, y)

2.3 nan


In [50]:
#ANSWER
pd.isna(x), pd.isna(y)

(False, True)

In [51]:
array = np.array([[1, np.nan, 3], [4, 5, np.nan]])
print(array)

[[ 1. nan  3.]
 [ 4.  5. nan]]


In [53]:
#ANSWER
pd.isna(array)

array([[False,  True, False],
       [False, False,  True]])

How is the pandas I/O parameter `na_values` used?

? ANSWER: 

## Data Profiling

### Counts

When there are categorical variables in a dataset we will want to know how many possible values there are in each column. (Nb. If the dataset is a sample of a larger one, our sample may not capture all possible values of every categorical.)

How many (different) seasons are in `bikes`?

In [54]:
#ANSWER
bikes.season.unique()


array([1, 2, 3, 4], dtype=int64)

### Ranges

Print the range of the `instant`, `dteday`, and `windspeed` columns: 

In [57]:
#ANSWER

bikes[['instant', 'dteday','windspeed']].agg([min, max])


instant      dteday  windspeed
min        1  2011-01-01     0.0000
max    17379  2012-12-31     0.8507

Compute and print the overall minimum and maximum of the numeric data columns:

In [59]:
bikes_min, bikes_max = (min(bikes.min(numeric_only=True)), max(bikes.max(numeric_only=True)))
bikes_min, bikes_max

(0.0, 17379.0)

### Quantiles

Pandas makes computing quantiles easy. This is how to get the median of a Series:

In [60]:
bikes['atemp'].quantile(0.5)

0.4848

Of course, the `quantiles` method can take a tuple as its argument. Compute the 10th, 25th, 50th, 75th, and 90th percentiles in one line of code: 

In [61]:
#ANSWER
bikes.atemp.quantile([0.10, 0.25, 0.5, 0.75, 0.9])

0.10    0.2424
0.25    0.3333
0.50    0.4848
0.75    0.6212
0.90    0.6970
Name: atemp, dtype: float64

### Cuts

Sometimes we want to split the sample not by the quantiles of the distribution but by the range of the data. Let's take a closer look at `atemp`:

In [62]:
type(bikes['atemp'])

pandas.core.series.Series

In [63]:
bikes.sample(5)

instant      dteday  season  yr  mnth  hr  holiday  weekday  \
849        850  2011-02-07       1   0     2  20        0        1   
13362    13363  2012-07-15       3   1     7  23        0        0   
8422      8423  2011-12-22       1   0    12  14        0        4   
12340    12341  2012-06-03       2   1     6   9        0        0   
11396    11397  2012-04-25       2   1     4   1        0        3   

       workingday  weathersit  temp   atemp   hum  windspeed  casual  \
849             1           2  0.32  0.3333  0.70     0.1045       6   
13362           0           1  0.72  0.6970  0.79     0.1343      25   
8422            1           2  0.46  0.4545  0.63     0.0000      23   
12340           0           1  0.60  0.6212  0.46     0.1940      70   
11396           1           1  0.42  0.4242  0.41     0.0000       8   

       registered  cnt  
849            82   88  
13362          66   91  
8422          136  159  
12340         230  300  
11396          17   25

Suppose we decide to sort these values into 4 bins of equal width, but we want to apply the resulting groups to the entire DataFrame. Basically, we need to add a row label that indcates which bin each sample belongs in. Let's call this label "atemp_level", and use the `cut` method to populate it:

In [64]:
atemp_level = pd.cut(bikes['atemp'], bins = 4)         
atemp_level

0        (0.25, 0.5]
1        (0.25, 0.5]
2        (0.25, 0.5]
3        (0.25, 0.5]
4        (0.25, 0.5]
            ...     
17374    (0.25, 0.5]
17375    (0.25, 0.5]
17376    (0.25, 0.5]
17377    (0.25, 0.5]
17378    (0.25, 0.5]
Name: atemp, Length: 17379, dtype: category
Categories (4, interval[float64]): [(-0.001, 0.25] < (0.25, 0.5] < (0.5, 0.75] < (0.75, 1.0]]

What is `atemp_level`?

In [ ]:
#ANSWER

#atemp_level is a series with 4 equal range categories generated by using  cut method.
# the category

Here is a random sample of `atemp_level`:

In [65]:
atemp_level.sample(5)          

5235        (0.5, 0.75]
14237       (0.5, 0.75]
9671     (-0.001, 0.25]
1679        (0.25, 0.5]
13504       (0.5, 0.75]
Name: atemp, dtype: category
Categories (4, interval[float64]): [(-0.001, 0.25] < (0.25, 0.5] < (0.5, 0.75] < (0.75, 1.0]]

So, by default, `cut` produces labels that indicate the bin boundaries for each element in the series it was applied to. Usually, we will specify labels that are appropriate to the discretisation we are applying:

In [66]:
atemp_level = pd.cut(bikes['atemp'], bins = 4, labels = ["cool", "mild", "warm", "hot"])
atemp_level.sample(5)          

5219     warm
2508     mild
15321    warm
4087     warm
6714     warm
Name: atemp, dtype: category
Categories (4, object): ['cool' < 'mild' < 'warm' < 'hot']

Incorporate the new `atemp_level` column into the `bikes` DataFrame and use it to count the number of "mild" `atemp` entries in `season` 2:

In [74]:
#ANSWER

bikes['atemp_level'] = atemp_level

bikes[(bikes.atemp_level == 'mild') &(bikes.season == 2)].season.count()

1829

*Nb. The `atemp_level` variable we created is what the R language calls a "factor". Pandas has introduced a new data type called "category" that is similar to R's factors.*

# Synthetic Data

Sometimes we may want to generate test data, or we may need to initalise a series, matrix, or data frame for input to an algorithm. Numpy has several methods we can use for this.

Execute the following, then check the shape and content of each variable:

In [75]:
# Creating arrays with initial values
a = np.zeros((3))
b = np.ones((1,3))
c = np.random.randint(1,10,(2,3,4))   # randint(low, high, size)
d = np.arange(4)
e = np.array( [[1,2,3,4], [5,6,7,8]] )

In [76]:
a


array([0., 0., 0.])

In [77]:
a.shape

(3,)

In [78]:
b

array([[1., 1., 1.]])

In [79]:
b.shape

(1, 3)

In [80]:
c

array([[[6, 9, 4, 5],
        [8, 2, 9, 9],
        [6, 9, 2, 2]],

       [[2, 6, 9, 4],
        [3, 8, 9, 8],
        [5, 6, 9, 5]]])

In [81]:
c.shape

(2, 3, 4)

In [82]:
c.ndim

3

In [83]:
d

array([0, 1, 2, 3])

In [84]:
d.shape

(4,)

In [85]:
e

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [86]:

e.shape

(2, 4)

In [87]:
c

array([[[6, 9, 4, 5],
        [8, 2, 9, 9],
        [6, 9, 2, 2]],

       [[2, 6, 9, 4],
        [3, 8, 9, 8],
        [5, 6, 9, 5]]])

In [ ]:
# Cleaning Data

## Load Data

Load rock.csv and clean the dataset.

In [88]:
rock = pd.read_csv('rock.csv')
rock

Song Clean ARTIST CLEAN Release Year  \
0                                Caught Up in You  .38 Special         1982   
1                                    Fantasy Girl  .38 Special          NaN   
2                                 Hold On Loosely  .38 Special         1981   
3                          Rockin' Into the Night  .38 Special         1980   
4                               Art For Arts Sake         10cc         1975   
...                                           ...          ...          ...   
2225                      She Loves My Automobile       ZZ Top          NaN   
2226                            Tube Snake Boogie       ZZ Top         1981   
2227                                         Tush       ZZ Top         1975   
2228                                   TV Dinners       ZZ Top         1983   
2229  WAITIN' FOR THE BUS/JESUS JUST LEFT CHICAGO       ZZ Top         1973   

                                               COMBINED  First?  Year?  \
0                       Caught Up in You by .38 Special       1      1   
1                           Fantasy Girl by .38 Special       1      0   
2                        Hold On Loosely by .38 Special       1      1   
3                 Rockin' Into the Night by .38 Special       1      1   
4                             Art For Arts Sake by 10cc       1      1   
...                                                 ...     ...    ...   
2225                  She Loves My Automobile by ZZ Top       1      0   
2226                        Tube Snake Boogie by ZZ Top       1      1   
2227                                     Tush by ZZ Top       1      1   
2228                               TV Dinners by ZZ Top       1      1   
2229  WAITIN' FOR THE BUS/JESUS JUST LEFT CHICAGO by...       1      1   

      PlayCount  F*G  
0            82   82  
1             3    0  
2            85   85  
3            18   18  
4             1    1  
...         ...  ...  
2225          1    0  
2226         32   32  
2227        109  109  
2228          1    1  
2229          2    2  

[2230 rows x 8 columns]

## Check Column Names

Check column names and clean.

In [89]:
rock.columns

Index(['Song Clean', 'ARTIST CLEAN', 'Release Year', 'COMBINED', 'First?',
       'Year?', 'PlayCount', 'F*G'],
      dtype='object')

In [90]:
rock.isnull().sum()

Song Clean        0
ARTIST CLEAN      0
Release Year    577
COMBINED          0
First?            0
Year?             0
PlayCount         0
F*G               0
dtype: int64

In [93]:
def clean_column_name(column_names):
    clean_column_names = []
    for c in column_names:
        c = c.lower().replace(' ', '_')
        c = c.lower().replace('*', '')
        c = c.lower().replace('?', '')
        clean_column_names.append(c)
        
    return clean_column_names

In [102]:
rock.columns = clean_column_name(rock.columns)
rock.columns

Index(['song_clean', 'artist_clean', 'release_year', 'combined', 'first',
       'year', 'playcount', 'fg'],
      dtype='object')

# Replace Null Values With 0

Check 'release' column whether this column have any null value or not. Replace null value with 0.

In [111]:
rock['release_year'].isnull().sum()

577

In [112]:
# create null mask to find all null rows in Release Year

null_mask = rock['release_year'].isnull()

# replave null valuesin Release Year with 0
rock.loc[null_mask,'release_year'] = 0


In [113]:
#check that all null values in relieas year 
rock.isnull().sum()

song_clean         0
artist_clean       0
release_year       0
combined           0
first              0
year               0
playcount          0
fg                 0
Release Year    1653
release-year    1653
dtype: int64

# Check Datatypes of Dataset

Check datatypes of the dataset. Is there any column which should be int instead of object? Fix the column. 

In [114]:
rock.dtypes

song_clean       object
artist_clean     object
release_year     object
combined         object
first             int64
year              int64
playcount         int64
fg                int64
Release Year    float64
release-year    float64
dtype: object

# Check Min, Max of Each Column

Is there any illogical value in any column? How can we fix that?

In [118]:
rock.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2230 entries, 0 to 2229
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   song_clean    2230 non-null   object 
 1   artist_clean  2230 non-null   object 
 2   release_year  2230 non-null   object 
 3   combined      2230 non-null   object 
 4   first         2230 non-null   int64  
 5   year          2230 non-null   int64  
 6   playcount     2230 non-null   int64  
 7   fg            2230 non-null   int64  
 8   Release Year  577 non-null    float64
 9   release-year  577 non-null    float64
dtypes: float64(2), int64(4), object(4)
memory usage: 174.3+ KB


In [ ]:
#release_year should be an int not object

In [119]:
rock.release_year.value_counts()

0                577
1973             104
1975              83
1977              83
1970              81
1971              75
1969              72
1980              70
1978              64
1979              63
1981              61
1967              61
1983              60
1976              56
1982              54
1984              51
1972              50
1974              48
1968              46
1985              39
1987              39
1986              37
1991              34
1989              32
1966              30
1988              29
1965              28
1994              25
1990              22
1993              19
1964              14
1992              14
1999              13
1995              10
1963               9
1996               9
1997               9
1998               6
2002               6
2005               5
2004               5
2012               5
2001               4
1962               3
2000               3
2007               3
2008               3
2011         

In [137]:
# Create a mask to find all rows with SONGFACTS.COM
song_facts_mask = rock['release_year'] == 'SONGFACTS.COM'
rock.loc[song_facts_mask, 'release_year'] = np.NaN

In [141]:
# Convert release year to numeric
rock['release_year'] = pd.to_numeric(rock['release_year'])

In [142]:
rock.dtypes

song_clean       object
artist_clean     object
release_year    float64
combined         object
first           float64
year            float64
playcount       float64
fg              float64
Release Year    float64
release-year    float64
dtype: object

# Write Some Functions

## Write a function that will take a row of a DataFrame and print out the song, artist, and whether or not the release date is < 1970

In [148]:
rock.loc[0,'song_clean']

'Caught Up in You'

In [163]:
def info(row):
    if rock.loc[row, 'release_year'] < 1970:
        print( rock.loc[row, 'song_clean'] + '_' + rock.loc[row, 'artist_clean'] + 'release date was before 1970')
    else:
        print( rock.loc[row, 'song_clean'] + ' by ' + rock.loc[row, 'artist_clean'] + ' release date was after 1970')
    

In [164]:
info(5)

Kryptonite by 3 Doors Down release date was after 1970


## Write a function that converts cells in a DataFrame to float and otherwise replaces them with np.nan

In [199]:
def column_conv(col):
    if type(col) == int or float:
        return float(col)
    else:
        return np.nan

    
    
    

In [200]:
column_conv('rock.release_year')

ValueError: could not convert string to float: 'rock.release_year'

## Apply these functions to your dataset

## Describe the new float-only DataFrame.



> 
>
>




>


>


>




---



---



> > > > > > > > > © 2019 Institute of Data


---



---



